FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

# Use this for development
CMD ["streamlit", "run", "--server.runOnSave", "true", "/app/app.py"]